# Generated by Django 2.2.5 on 2021-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Movie genre', max_length=15)),
                ('genre_id', models.IntegerField(help_text='Globally Known Genres IDs', null=True, unique=True, verbose_name='Global Genre ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=10, verbose_name='IMDB ID')),
                ('tmdb_id', models.IntegerField(help_text='TMDB movie ID', null=True, unique=True, verbose_name='TMDB ID')),
                ('title', models.CharField(max_length=50)),
                ('plot', models.TextField(verbose_name='Synopsis')),
                ('poster', models.CharField(max_length=100)),
                ('trailer_url', models.TextField(help_text='Url for the movie trailer', null=True, verbose_name='Trailer')),
                ('directors', models.TextField(blank=True, null=True, verbose_name='Movie Directors')),
                ('release_date', models.CharField(blank=True, max_length=15, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('web_rip_720p_url', models.TextField(blank=True, null=True, verbose_name='WEB RIP 720P URL')),
                ('web_rip_1080p_url', models.TextField(blank=True, null=True, verbose_name='WEB RIP 1080P URL')),
                ('blu_ray_720p_url', models.TextField(blank=True, null=True, verbose_name='BLU RAY 720P URL')),
                ('blu_ray_1080p_url', models.TextField(blank=True, null=True, verbose_name='BLU RAY 1080P URL')),
                ('upload_timestamp', models.PositiveIntegerField(default=1620409543.7753472)),
                ('quality', models.CharField(choices=[('HD', '720p'), ('FHD', '1080p'), ('QHD', '1440p')], default='720p', help_text='Video quality of the movie', max_length=10)),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
            options={
                'ordering': ['upload_timestamp'],
            },
        ),
    ]
